-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Fornecedor"
(
    "id_Fornecedor" smallint NOT NULL,
    "Razão social" character varying(50)[] COLLATE pg_catalog."default" NOT NULL,
    "CPF/CNPJ" character varying(18)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Fornecedor_pkey" PRIMARY KEY ("id_Fornecedor")
);

CREATE TABLE IF NOT EXISTS public."Pedidos"
(
    "id_Fornecedor" smallint NOT NULL,
    "idProduto" integer NOT NULL,
    "DataPedido" date NOT NULL,
    "ValorTotal" money NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Produtos"
(
    "idProduto" integer NOT NULL,
    "Categoria" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Valor" money NOT NULL,
    CONSTRAINT "Produtos_pkey" PRIMARY KEY ("idProduto")
);

ALTER TABLE IF EXISTS public."Pedidos"
    ADD CONSTRAINT "idProduto" FOREIGN KEY ("idProduto")
    REFERENCES public."Produtos" ("idProduto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedidos"
    ADD CONSTRAINT "id_Fornecedor" FOREIGN KEY ("id_Fornecedor")
    REFERENCES public."Fornecedor" ("id_Fornecedor") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;